apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
  labels:
    app: url-shortener
spec:
  replicas: 2
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
      - name: url-shortener
        image: gcr.io/YOUR_PROJECT_ID/url-shortener:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: "YOUR_VM_IP_ADDRESS"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "url_shortener"
        - name: DB_USER
          value: "url_user"
        - name: DB_PASSWORD
          value: "url_pass"
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
